### ISSUE TITLE
Refactor Arduino codes

### ISSUE THREAD

**Issue by Emivvvvv** [Emivvvvv/gercek_patron#3]
The code is almost ready but open to improvements. Some parts should be refactored. This issue is open for PRs!

**Comment by Jsuryaboi-08** [comment]
what file and what branch?

**Comment by Jsuryaboi-08** [comment]
is there anything more to be done? if so i would be glad to help if i could.

**Comment by Emivvvvv** [comment]
> is there anything more to be done? if so i would be glad to help if i could.

Thanks for your interest @Jsuryaboi-08, We were going to use this in our project, but we switched platforms, so we won't need this if we don't change our minds again. However, feel free to look at the code and send a PR if you see marginal improvements in both the Go and Arduino code.

Have a great day!
